// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Artwalk documents
 */
interface ArtwalkDocumentData {
  /**
   * Name field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Artwork name (main title)
   * - **API ID Path**: artwalk.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Sub Name field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Artwork subtitle or alternative name
   * - **API ID Path**: artwalk.subName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subName: prismic.KeyTextField;

  /**
   * Thumbnail Image field in *Artwalk*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artwalk.thumb
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumb: prismic.ImageField<never>;

  /**
   * Material field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Artwork material
   * - **API ID Path**: artwalk.material
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  material: prismic.KeyTextField;

  /**
   * Category field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Category slug (e.g., outdoor-sculpture-park)
   * - **API ID Path**: artwalk.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Description field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Detailed description of the artwork
   * - **API ID Path**: artwalk.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Detail Title field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title for detail view
   * - **API ID Path**: artwalk.detailTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detailTitle: prismic.KeyTextField;

  /**
   * Detail Info field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Additional information about the artwork
   * - **API ID Path**: artwalk.detailInfo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detailInfo: prismic.KeyTextField;

  /**
   * Detail Author field in *Artwalk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Artist or creator name
   * - **API ID Path**: artwalk.detailAuthor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  detailAuthor: prismic.KeyTextField;

  /**
   * Detail Image field in *Artwalk*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artwalk.detailImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  detailImage: prismic.ImageField<never>;
}

/**
 * Artwalk document from Prismic
 *
 * - **API ID**: `artwalk`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtwalkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArtwalkDocumentData>,
    "artwalk",
    Lang
  >;

/**
 * Item in *Homepage → Split Banner Sections*
 */
export interface HomepageDocumentDataSplitBannerSectionsItem {
  /**
   * Section Title field in *Homepage → Split Banner Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section title
   * - **API ID Path**: homepage.split_banner_sections[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Section Description field in *Homepage → Split Banner Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section description
   * - **API ID Path**: homepage.split_banner_sections[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Text field in *Homepage → Split Banner Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Call to action text
   * - **API ID Path**: homepage.split_banner_sections[].cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * Section Image field in *Homepage → Split Banner Sections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.split_banner_sections[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Alt Text field in *Homepage → Split Banner Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Image alt text
   * - **API ID Path**: homepage.split_banner_sections[].image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;
}

/**
 * Item in *Homepage → Grid Images Items*
 */
export interface HomepageDocumentDataGridImagesItemsItem {
  /**
   * Grid Image field in *Homepage → Grid Images Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.grid_images_items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Alt Text field in *Homepage → Grid Images Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Image alt text
   * - **API ID Path**: homepage.grid_images_items[].image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;

  /**
   * Image Title field in *Homepage → Grid Images Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Image title
   * - **API ID Path**: homepage.grid_images_items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image Description field in *Homepage → Grid Images Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Image description
   * - **API ID Path**: homepage.grid_images_items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Hero Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hero section title
   * - **API ID Path**: homepage.hero_title
   * - **Tab**: Hero Section
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero Subtitle field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hero section subtitle
   * - **API ID Path**: homepage.hero_subtitle
   * - **Tab**: Hero Section
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_subtitle: prismic.RichTextField;

  /**
   * Hero Background Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_background_image
   * - **Tab**: Hero Section
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_background_image: prismic.ImageField<never>;

  /**
   * Hero Logo field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_logo
   * - **Tab**: Hero Section
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_logo: prismic.ImageField<never> /**
   * About Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About section title
   * - **API ID Path**: homepage.about_title
   * - **Tab**: About Section
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  about_title: prismic.KeyTextField;

  /**
   * About Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: About section description
   * - **API ID Path**: homepage.about_description
   * - **Tab**: About Section
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about_description: prismic.RichTextField;

  /**
   * About Button Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About section button text
   * - **API ID Path**: homepage.about_button_text
   * - **Tab**: About Section
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_button_text: prismic.KeyTextField /**
   * Focus Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Focus section title
   * - **API ID Path**: homepage.focus_title
   * - **Tab**: Center Banner Section
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  focus_title: prismic.KeyTextField;

  /**
   * Focus Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Focus section description
   * - **API ID Path**: homepage.focus_description
   * - **Tab**: Center Banner Section
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  focus_description: prismic.RichTextField;

  /**
   * Focus Button Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Focus section button text
   * - **API ID Path**: homepage.focus_button_text
   * - **Tab**: Center Banner Section
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  focus_button_text: prismic.KeyTextField;

  /**
   * Focus Background Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.focus_background_image
   * - **Tab**: Center Banner Section
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  focus_background_image: prismic.ImageField<never>;

  /**
   * Aspect Ratio field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Aspect ratio
   * - **API ID Path**: homepage.focus_aspect_ratio
   * - **Tab**: Center Banner Section
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  focus_aspect_ratio: prismic.KeyTextField /**
   * Split Banner Sections field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.split_banner_sections[]
   * - **Tab**: Split Banner Section
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */;
  split_banner_sections: prismic.GroupField<
    Simplify<HomepageDocumentDataSplitBannerSectionsItem>
  > /**
   * Grid Images Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Grid images section title
   * - **API ID Path**: homepage.grid_images_title
   * - **Tab**: Grid Images Section
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  grid_images_title: prismic.KeyTextField;

  /**
   * Grid Images Items field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.grid_images_items[]
   * - **Tab**: Grid Images Section
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grid_images_items: prismic.GroupField<
    Simplify<HomepageDocumentDataGridImagesItemsItem>
  >;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Navigation Menu → Menu Items → Submenus*
 */
export interface NavigationMenuDocumentDataItemsSubsItem {
  /**
   * Submenu ID field in *Navigation Menu → Menu Items → Submenus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Unique identifier for submenu
   * - **API ID Path**: navigation_menu.items[].subs[].id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  id: prismic.KeyTextField;

  /**
   * Submenu Name field in *Navigation Menu → Menu Items → Submenus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Submenu item name
   * - **API ID Path**: navigation_menu.items[].subs[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Submenu Href field in *Navigation Menu → Menu Items → Submenus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Submenu item link
   * - **API ID Path**: navigation_menu.items[].subs[].href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  href: prismic.KeyTextField;
}

/**
 * Item in *Navigation Menu → Menu Items*
 */
export interface NavigationMenuDocumentDataItemsItem {
  /**
   * Menu Label field in *Navigation Menu → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Menu item label
   * - **API ID Path**: navigation_menu.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Menu Href field in *Navigation Menu → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Menu item link (e.g., /, /artwalk)
   * - **API ID Path**: navigation_menu.items[].href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  href: prismic.KeyTextField;

  /**
   * Submenus field in *Navigation Menu → Menu Items*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.items[].subs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  subs: prismic.NestedGroupField<
    Simplify<NavigationMenuDocumentDataItemsSubsItem>
  >;
}

/**
 * Content for Navigation Menu documents
 */
interface NavigationMenuDocumentData {
  /**
   * Menu Items field in *Navigation Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<NavigationMenuDocumentDataItemsItem>>;
}

/**
 * Navigation Menu document from Prismic
 *
 * - **API ID**: `navigation_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationMenuDocumentData>,
    "navigation_menu",
    Lang
  >;

export type AllDocumentTypes =
  | ArtwalkDocument
  | HomepageDocument
  | NavigationMenuDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Title field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About title
   * - **API ID Path**: about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: About description
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button text
   * - **API ID Path**: about.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About section with title, description and button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hero title
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hero subtitle
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Logo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with title, subtitle and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArtwalkDocument,
      ArtwalkDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSplitBannerSectionsItem,
      HomepageDocumentDataGridImagesItemsItem,
      NavigationMenuDocument,
      NavigationMenuDocumentData,
      NavigationMenuDocumentDataItemsSubsItem,
      NavigationMenuDocumentDataItemsItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
    };
  }
}
